COLOR_BARRA_SUPERIOR = "#1f2329"
COLOR_MENU_LATERAL = "#2a3138"
COLOR_CUERPO_PRINCIPAL = "#f1faff"
COLOR_MENU_CURSOR_ENCIMA = "#2f88c5"

azul_medio_oscuro = "#28242c"  ##COLOR DE LA BARRA SUPERIOR, DEL MENU LATERAL, COLOR OPCIONAL DE BOTON
gris = "#484c4c" ## COLOR DEL CUERPO PRINCIPAL
azul_mas_clarito = "#2f88c5"  ##COLOR DEL MENU ENCIMA
oscuro = "#101414" ## COLOR LABEL DEL BOTON
celeste_pero_oscuro = "#246474"  ##COLOR DEL DESPLEGABLE DE COMBOBOX
