azul_medio_oscuro = "#28242c"  ##COLOR DE LA BARRA SUPERIOR, DEL MENU LATERAL, COLOR OPCIONAL DE BOTON
gris = "#484c4c" ## COLOR DEL CUERPO PRINCIPAL
azul_mas_clarito = "#2f88c5"  ##COLOR DEL MENU ENCIMA
oscuro = "#101414" ## COLOR LABEL DEL BOTON
celeste_pero_oscuro = "#246474"  ##COLOR DEL DESPLEGABLE DE COMBOBOX
